version: '3.8'
services:
  db:
    container_name: mysqldb
    image: mysql/mysql-server
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poc1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
volumes:
  db_data: